server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://bitmoi.com.s3-website.ap-northeast-2.amazonaws.com/'
            allow-credentials: true #추가
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
      routes:
        - id: user login, join
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/login,/user/join,/user/check
        - id: user wallet
          uri: lb://USER-SERVICE
          predicates: # 조건절
            - Path=/user/wallet
          filters:
            - JwtAdminAuthVerifyFilter
        - id: user wallet
          uri: lb://ORDER-SERICE
          predicates: # 조건절
            - Path=/
          filters:
            - JwtAdminAuthVerifyFilter

jwt:
  secret: Y29kZXN0YXRlcy1iaXRodW1iLW1zYS10ZWFtLW1lbWJlci1zcHJpbmctYm9vdC13ZWJmbHV4LWp3dC1zZWNyZXQ=
