server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
      routes:
        - id: user login, join
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/login,/user/join,/user/check,/user/ranking,/user/asset/*
        - id: user wallet
          uri: lb://USER-SERVICE
          predicates: # 조건절
            - Path=/user/wallet
          filters:
            - JwtAdminAuthVerifyFilter
        - id: order
          uri: lb://ORDER-SERICE
          predicates: # 조건절
            - Path=/orderbook,/orderbook/user,/orders,/order/cancel/*
          filters:
            - JwtAdminAuthVerifyFilter
        - id: quotation
          uri: lb://QUOTATION-APP
          predicates: # 조건절
            - Path=/quotations/refresh
        - id: EXECUTION
          uri: lb://EXECUTION-SERVICE
          predicates: # 조건절
            - Path=/executions/*
        - id: bithum
          uri: https://api.bithumb.com/public/ticker/{order_currency}_{payment_currency}
          predicates: # 조건절
            - Path=/bithum/{order_currency}/{payment_currency}

jwt:
  secret: Y29kZXN0YXRlcy1iaXRodW1iLW1zYS10ZWFtLW1lbWJlci1zcHJpbmctYm9vdC13ZWJmbHV4LWp3dC1zZWNyZXQ
