server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user login, join
          uri: http://localhost:8080/
          predicates:
            - Path=/user/login,/user/join,/user/check
        - id: user wallet
          uri: http://localhost:8080/
          predicates: # 조건절
            - Path=/user/wallet
          filters:
            - JwtAdminAuthVerifyFilter

jwt:
  secret: Y29kZXN0YXRlcy1iaXRodW1iLW1zYS10ZWFtLW1lbWJlci1zcHJpbmctYm9vdC13ZWJmbHV4LWp3dC1zZWNyZXQ=
